### ISSUE TITLE
Providing possiblity for automatic deleting of groups.

### ISSUE THREAD

**Issue by mtstv** [Netcentric/accesscontroltool#110]
It would be great to have an OSGI config with configurated path to yaml files where groups defined to be  deleted automaticaly with their ACEs at the end of execute() method.

A client has a lot of mandators which changed (new/deleted/renamed) from time to time. Also not only the name of groups, but also the number of groups for different mandators also changed. To analyse which groups are not needed anymore and must be deleted manually (over AC Tool JMS or GUI) together with their ACEs involves a lot of time and not possible on the production by some reasons.

**Comment by ghenzler** [comment]
The `migrateFrom` property deletes the groups after taking over users: https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md#group-migration 

But if you want to delete a whole set of groups completely (let's say for a tenant that is no longer needed), this would indeed be a new feature. But rather than using an OSGi config I would probably introduce a new config element, maybe `obsoleteGroups` in `global`:

```
 - global:
      - obsoleteGroups:
           - groupToDelete1
           - groupToDelete2
           - groupToDelete3
           - groupToDelete4
           - groupToDelete5
``` 
Doing it like this (a true yaml list and not a comma-separated list) would automatically allow for FOR loops and IF conditions.

**Comment by mtstv** [comment]
Yes, I dont' want to migrate some groups. 
I want to delete a huge set of groups and their ACLs completely and automaticaly, because tenants don't exists anymore or groups concept has been changed (some tenant groups are not needed anymore).
With obsoleteGroups element it would be good.

**Comment by mtstv** [comment]
About LOOP do you meen that the next will works?

```
- global_config:
    - obsoleteGroups:
        - FOR groupToDelete IN [groupToDelete1, groupToDelete2, groupToDelete3]:
            - ${groupToDelete}

```

**Comment by ghenzler** [comment]
@mtstv yes (although the above example would not win much, you could just list the groups explicitly). It does make sense for groups automatically derived from content structure [1] or if you concatenate group names in nested loops.

[1] https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#loops-derived-from-content-structure-since-18x

**Comment by ghenzler** [comment]
Created https://github.com/Netcentric/accesscontroltool/pull/122 - instead of `global_config` a new root element `obsolete_authorizables` is used (`global_config` is more meant for simple settings, `obsolete_authorizables` might become quite complex since  FOR/IF syntax can be used):

```
- obsolete_authorizables:
      - groupToDelete1
      - groupToDelete2
      - groupToDelete3
      - groupToDelete4 
```

**Comment by ghenzler** [comment]
Merged https://github.com/Netcentric/accesscontroltool/pull/122
