### ISSUE TITLE
Question about deletion, incremental update

### ISSUE THREAD

**Issue by chetanyajain** [Netcentric/accesscontroltool#126]
I have been using this tool to try out various things and did a demo to the wider audience to start using this for better maintenance of ACLs. However here are some of the important questions that camp up during the discussion and would need to understand if the tool can support (or may be for future)

1.  First time deployment is definitely a simplified approach however for any on-going minor changes it re-deploys all the rules which is tricky especially in production since it deletes all the ACEs and adds them. Is there any possibility to support incremental changes?

2. Deletion of ACEs and adding them again, even for minor changes, can call for regression of entire system. Any better approach that can be followed here?

3. Advanced feature like loop is an amazing feature. But to use it in a dynamic manner (i.e. on site creation), the entire script have to be re-executed again i.e. delete and re-add. Are there any best practices over here?

4. Is this tool production ready or needs to be thoroughly tested before go live? Is it been used by any customer in PROD?

5. What are the features planned for future release, any roadmap?

Thanks & Regards,
Chetanya

**Comment by mtstv** [comment]
Hi,

1. At the moment no. But from experience it is simpler to delete and setup ACEs again in appropriate order.

2. We had no troubles. It is more important to setup the right rights and groups concept.

3.  You can use loops not only in dynamic manner if you know all node names of your future sites. But in this case you must re-execute AC Tool again. It must belongs to every your deployment process. Another solution is to setup groups and rights concept where ACE incl. rep:glob property for site nodes will be defined in the top nodes.

4. Yes, AC Tool used already since early versions for many global customers with a huge number (tousends) of tenants on one AEM cluster on PROD. But some versions had errors in some features which were fixed in later versions and for some erros there were workarounds.

5. see issue #120 and #110

**Comment by ghenzler** [comment]
An incremental update has been discussed already, I added #127 for it. 

We use the ACTool for pretty much all Netcentric projects in production. Sometime we use only post-deployment runs, for some projects we have nightly runs of the AC Tool.

**Comment by chetanyajain** [comment]
Thanks for looking into this and adding the new enhancement for future release.

The main challenge is definitely performance and writing / touching the nodes even if its not modified.

**Comment by ghenzler** [comment]
> The main challenge is definitely performance and writing / touching the nodes even if its not modified.

@chetanyajain with v2.0.0 this is now changed (see #155)

**Comment by chetanyajain** [comment]
@ghenzler Thanks for the most awaited release. I will test the feature and give you the feedback.
