### ISSUE TITLE
Setting ACL based on sling:resourceType

### ISSUE THREAD

**Issue by tobiaslippert** [Netcentric/accesscontroltool#196]
Hi,
I have the requirement to set ACLs on paths created during runtime. Unfortunately the nodes below level 1 have different privileges, so inheritance is not possible. All nodes below level 1 have different sling:resourceTypes, so I like to base the decision which rights to set on this. 

I want to loop over all nodes below level 1 and set the rights based on the sling:resourceType. The restriction: sling:resourceTypes does not work. I am using AEM6.2. Is that an issue or is there another way to meet the requirements? Thanks

**Comment by ghenzler** [comment]
@tobiaslippert You have two options here:

- You can use https://sling.apache.org/documentation/bundles/sling-oak-restrictions.html (those restrictions are supported by the AC Tool, but you will need to install the sling extension bundle). The big advantage is that the restriction can be set to the root path and after additional content was created, you do not need to run the AC Tool again
- Alternatively you can loop over sub pages, and attach permissions based on resource type using `- FOR site IN CHILDREN OF /content/myPrj:`  and multiple `- IF ${site['jcr:content']['sling:resourceType'] eq 'myProj/myComp'}:` underneath. This is slightly better from a performance perspective, however newly created content will not carry the ACLs until the AC Tool is run (you can use the API though to apply the ACLs to certain root paths only since [version 1.9.2](https://github.com/Netcentric/accesscontroltool/releases/tag/1.9.2) )

**Comment by ghenzler** [comment]
Please reopen if you need more information or you have an improvement suggestion
