### ISSUE TITLE
AC Tool Removes Group Membership for communities-user-admin on AEM 6.2

### ISSUE THREAD

**Issue by ichirital** [Netcentric/accesscontroltool#230]
Hello,
 
We’re using the Netcentric AC Tool release 2.0.0 to manage custom permissions in our AEM 6.2 project.
 
I’ve recently run into an issue with it while configuring integration between Livefyre and AEM Sites, by following instructions at [1]. This was working as expected on a fresh AEM 6.2 instance, however, as soon as out netcentric YAML configuration was installed, a “Please configure the Livefyre network” message would appear on the page instead of the Livefyre component.
 
After investigation, it turned out that Livefyre uses a service user mapping to the `communities-user-admin user`. On an out of the box AEM installation, this is member of several groups (including `Communities Administrators` and `User Administrators`) which gives it the required access to some /etc and /content paths. After installation of the netcentric YAML configuration, this user is only member of `everyone` group. See screenshots at [2].
 
What I’m getting at is an open question with regards to best practices of using this tool in the context of a changing AEM environment: we might upgrade to AEM 6.3, or install CFPs or other packages that end up installing permissions or group memberships that the Netcentric AC Tool might end up wiping out as far as I’m gathering.
 
Furthermore, when using the `groupBasedDump` method available in JMX the paths are returned in a random order (there’s either a groupBasedDump or a pathBasedDump, but not an ORDER BY group, then path ☺) and this makes YAML file diffs with the current configuration a real pain.

Also, just to remove any doubts on a possible wrong configuration of out YAML file, I tried getting a full `groupBasedDump` from a freshly configured instance and re-install **exactly** the same file into the instance and this indeed resets (at least) the group membership for the `communities-user-admin` user. For me, this rules out a problematic rule or something I may have missed adding to the file.
 
Any insights into how to make best use of this tool without running into risks of removing OOTB functionality? Or is this a bug that needs to be addressed?
 
Many thanks,
 
Regards,
Irina
 
[1] http://answers.livefyre.com/product/livefyre-for-adobe-experience-manager-aem/livefyre-for-adobe-experience-manager
[2]
 
Before: 
![image](https://user-images.githubusercontent.com/15053333/32721213-a6252348-c85d-11e7-916a-b65f9d45a454.png)

After:
![image](https://user-images.githubusercontent.com/15053333/32721222-afaa1c0c-c85d-11e7-9504-ea6cc48a0dca.png)

**Comment by ghenzler** [comment]
Hi Irina, 

here are a few hints about best practices:

- Always upgrade to latest version if possible (2.0.2 currently)
- If you are migrating to Use the AC Tool, use groupBasedDump() to get fragments that you can use for an actual configuration. **It is always never a good idea to install a dump result 1-to-1 back into an instance** (since you mentioned correctly that this would wipe out changes that come with upgrades/service packs)
- Make a qualified decision in your project which authorizables you manage and which ones you don't manage with the AC Tool (typically project-specific groups you manage, anything ootb AEM you do not manage
  - Generally the tool only touches authorizables as mentioned in the configuration and leaves everything else unchanged
  -  If you have to maintain relationships between managed and non-managed groups, use `keepExistingMembershipsForGroupNamesRegEx ` (see https://github.com/Netcentric/accesscontroltool/blob/develop/docs/AdvancedFeatures.md#configure-memberships-to-dynamic-groups)

**Comment by kwin** [comment]
This is most probably related to #236.

**Comment by ghenzler** [comment]
@ichirital Please re-open if you have further questions/problems.

**Comment by ichirital** [comment]
Thank you @ghenzler, that makes sense. I will look into cleaning up our YAML definitions.
