### ISSUE TITLE
First name & last name should be separate properties

### ISSUE THREAD

**Issue by henrykuijpers** [Netcentric/accesscontroltool#231]
Currently, the tool supports entering a "name", which should be the full name (first name, middle name, last name). 

Then, when processing, in case of groups, it puts this full name.
In case of users, it splits the string based on the last occurring space character.

That is incorrect in these cases:
Sebastian van der Broek (expected: "Sebastian", "van der Broek", actual: "Sebastian van der", "Broek")
Jan Jaap van der Wal (expected: "Jan Jaap", "van der Wal", actual: "Jan Jaap van der", "Wal")

Solution:
Add firstName and lastName property, so they can be configured separately, as it will never be possible to correctly parse all full names into the correct first name and last name.

**Comment by ghenzler** [comment]
Good point - we have not had much pain around this since we normally only use the tool to create test users, but it is easy enough to support this in https://github.com/Netcentric/accesscontroltool/blob/46e2b6dfd87d1c3b4aca4b6169ddc413f4c32af9/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/authorizableinstaller/impl/AuthorizableInstallerServiceImpl.java#L583

**Comment by mtstv** [comment]
You can also use "profileContent" property to define any user props you need like

    - user_config:
        - sebvanderbroek:
            - name:
              password: blablabla
              isMemberOf: my-editors
              path: /home/users/myproject/v
              profileContent: <jcr:root jcr:primaryType="nt:unstructured" sling:resourceType="cq/security/components/profile" givenName="Sebastian" familyName="van der Broek"/>
              preferencesContent: <jcr:root jcr:primaryType="nt:unstructured" language="nl"/>

**Comment by mtstv** [comment]
this will work well for some "van der XXX" users
:-)

**Comment by henrykuijpers** [comment]
That's what I ended up doing indeed.

Nevertheless, the functionality that exists without using ' profileContent' for it still feels broken.

**Comment by mtstv** [comment]
so, at least there is a solution which works now

**Comment by ghenzler** [comment]
`profileContent` works but I have to admit it is rather a workaround. 
@henrykuijpers instead of introducing two new properties (in a class that is also used for groups, and for that case it does not make sense) I have a better idea: A comma can be used to specify the split between first/lastname.  See [proposed documentation in PR](https://github.com/Netcentric/accesscontroltool/blob/041cd246e9e5b0c8dd0adf8a938ba041c54c3ae1/docs/Configuration.md#configuration-of-users)
