### ISSUE TITLE
oak index package still needed?

### ISSUE THREAD

**Issue by wimsymons** [Netcentric/accesscontroltool#426]
According to #386 and #392, it is no longer needed to install the Oak index package.
But the README still mentions it is recommended.

We have approx. 32 million nodes in our repository now.
What is the latest recommended approach? Dump it or keep it?

And if the recommended approach is to dump it, I would suggest to update the README accordingly.

**Comment by ghenzler** [comment]
The recommended approach is to keep it if you have a large repository. You can turn on debug logging for `biz.netcentric.cq.tools.actool.helper.QueryHelper`, then https://github.com/Netcentric/accesscontroltool/blob/03fc6302086c5b9f318d8ac93a147ecc3d3d97cb/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java#L103 will show you what query was used (depending on if the oak index was available) and https://github.com/Netcentric/accesscontroltool/blob/03fc6302086c5b9f318d8ac93a147ecc3d3d97cb/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/helper/QueryHelper.java#L116 will log the time. 

With the OAK index installed, you can also just run 
```
SELECT * FROM [rep:ACL]
```
and 
```
SELECT ace.* FROM [rep:ACE] AS ace WHERE ace.[rep:principalName] IS NOT NULL
```
to get an idea on how the performance is different (the actual code runs the query per sub path, but the above queries will show you what the difference is for you (the second query is not so nice because it queries all ACE entries instead of the ACLs themselves, but this has the advantage that it uses the ootb index available for `rep:ACE`)

**Comment by wimsymons** [comment]
Thanks for the update! We’ll keep them.
