### ISSUE TITLE
Wrong Sling ServiceUserMapper configuration for JcrInstallUrlHandler

### ISSUE THREAD

**Issue by kwin** [Netcentric/accesscontroltool#471]
In https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-package/src/main/jcr_root/apps/netcentric/actool/config/org.apache.sling.serviceusermapping.impl.ServiceUserMapperImpl.amended-ncActoolSystemUser.config there is a user mapping defined for `BSN`:`biz.netcentric.cq.tools.accesscontroltool.bundle` and `subServiceName`:`actool`.

This does not apply everywhere as in some places in the source code where service resource resolver or system session is retrieved `null` is used as `subServiceName`.

This is https://github.com/Netcentric/accesscontroltool/search?q=loginService&unscoped_q=loginService and https://github.com/Netcentric/accesscontroltool/search?q=getServiceResourceResolver&unscoped_q=getServiceResourceResolver.

Therefore I am always getting failures like `org.apache.sling.api.resource.LoginException: Cannot derive user name for bundle biz.netcentric.cq.tools.accesscontroltool.bundle [591] and sub service null at org.apache.sling.resourceresolver.impl.ResourceResolverFactoryImpl.getServiceResourceResolver(ResourceResolverFactoryImpl.java:79) at biz.netcentric.cq.tools.actool.impl.JcrInstallUrlHandler.activate(JcrInstallUrlHandler.java:39) at ...`

**Comment by kwin** [comment]
It seems only https://github.com/Netcentric/accesscontroltool/blob/develop/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/JcrInstallUrlHandler.java#L39 is affected, but I am still wondering why we are using explicit sub service names
@santiagozky Do you remember why you haven't relied on BSN only but instead on BSN + sub service name from the beginning at https://github.com/Netcentric/accesscontroltool/commit/ea7d8a320f8f2ef891ab32446fd9fce8666d0b3c#diff-1e04c36503b24aa8535bcfed571fe429.

**Comment by ghenzler** [comment]
@kwin Using the subServiceName was never required I suppose but it was just reasonable to use one in case some functionality would get their own service user. 

So instead of changing so many places, why don't you just pass in a map with `sling.service.subservice` (see https://helpx.adobe.com/experience-manager/6-3/sites/developing/using/reference-materials/javadoc/org/apache/sling/api/resource/ResourceResolverFactory.html#getServiceResourceResolver(java.util.Map)) at https://github.com/Netcentric/accesscontroltool/blob/13d6126acabfdf8f7220bf48e06d422bde2128a1/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/impl/JcrInstallUrlHandler.java#L39 to fix it?
