### ISSUE TITLE
Component that opens up app to DOS type attacks

### ISSUE THREAD

**Issue by joestieg** [Netcentric/accesscontroltool#485]
During a scan of the accesscontroltool-package-2.5.5.zip with Nexus IQ, we see a security violation with SnakeYAML that opens up the app to DOS type attacks. (please see attachment). Is it possible to upgrade this to version 1.27?
[generic_scan-Build-20200924-092726.pdf](https://github.com/Netcentric/accesscontroltool/files/5276550/generic_scan-Build-20200924-092726.pdf)

**Comment by kwin** [comment]
For the record: https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion is the underlying issue (mentioned in http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-18640). The issue is fixed in 1.26 or newer. All changes since 1.13 (https://github.com/Netcentric/accesscontroltool/blob/4ab7b155a621ef623e9c9353fe6075d1e0e7a1c3/pom.xml#L257) are listed in  https://bitbucket.org/asomov/snakeyaml/wiki/Changes

**Comment by joestieg** [comment]
Thanks for adding this to next release.

**Comment by joestieg** [comment]
Added to next release.

**Comment by kwin** [comment]
@joestieg Please don't close as this is not yet fixed.

**Comment by kwin** [comment]
PR at #486

**Comment by kwin** [comment]
Would be good to include `dependency-check-maven` in the build (at least during CI) to detect such issues earlier.

**Comment by ghenzler** [comment]
PR #486 is merged
