### ISSUE TITLE
Space in JMX id "ac installation" is an issue on some systems

### ISSUE THREAD

**Issue by seuck** [Netcentric/accesscontroltool#50]
Some servers are configured to do not allow spaces in URLs.
As AC Tool JMX id contains a space those servers will return a 404 error loading AC Tool JMX console and URLs used to trigger its functionalities.

Either remove the space or replace with a URL compliant separator.

**Comment by ghenzler** [comment]
I would suggest switching to  biz.netcentric.cq.tools:type=ACTool (this is consistent to e.g. /system/console/jmx/com.adobe.granite:type=Repository). For backward compatibility we can support the old objectname for a few more versions (by having two JMX Beans, those beans just route requests to AceService)

**Comment by seuck** [comment]
It seems standard Adobe dispatcher config from here https://docs.adobe.com/docs/en/dispatcher/disp-config.html is sufficient to reproduce this problem.
Wrongly encoded spaces are transformed by Apache by default to fix them.

**Comment by ghenzler** [comment]
After a discussion with @kwin: We think it's best to just change the JMX Bean name to biz.netcentric.cq.tools:type=ACTool without remaining backwards compatible here - this means that project that use scripts to trigger the execute method will have to change the URL as well. However this is acceptable because it fails with a clear message and it is easy to fix.
