### ISSUE TITLE
Deployment of aem-acl takes long time and leads to error

### ISSUE THREAD

**Issue by Pavan-Allianz** [Netcentric/accesscontroltool#522]
### Deployment of platform-aem-acl takes long time and leads to error
While the time of AEM 6.5.5 upgrade we had a blocker issue which somehow got past, but this issue is recurring and will be blocker again for continuous delivery in future.

Please analyze why this package installation is consuming so much time and reduce it to an acceptable time may be under 60 seconds.

|AEM Version | Access Control Tool | Installation Time|
|6.5.4 | 2.3.2 | 40.2 second|
|6.5.4 | 2.5.4/2.5.5 | 41 second|
|6.5.5 | 2.3.2 | >1.1 minute|
|6.5.5 | 2.5.4/2.5.5 | > 1.1 minute|

There could be an underlying issue that is not showing up, but the problem is persistent. 

[acl_performance_difference.zip](https://github.com/Netcentric/accesscontroltool/files/5635873/acl_performance_difference.zip)

Thank you

**Comment by kwin** [comment]
Hi @Pavan-Allianz, this is Open-Source with only best effort support. You need to actually debug the issue a bit on your side and outline, which code piece is especially slow.

**Comment by ghenzler** [comment]
@Pavan-Allianz With version 2.7.1 #503 will bring some improvement also for you. 

However looking at your logs the main difference is that loading the configuration takes almost half the execution time (e.g. `Loaded configuration in 30.8sec` and `Successfully applied AC Tool configuration in 1.1min` in log file `6.5.5_ac_2.5.4_install.log`). For the two 6.5.4 logs this is always less (~ 4sec). Please debug your setup to find out what the root cause of this issue is
