### ISSUE TITLE
AEMaaCS: Unsupported Repository Structure - Package Structure

### ISSUE THREAD

**Issue by chetanyajain** [Netcentric/accesscontroltool#541]
Hi Team,

Per the Cloud Guidelines we need to add all the vendor packages /apps/project-vendor-packages/container/install/<actool>.zip. However the actool package doesn't have "all" package that splits mutable & immutable content. Per the Best Practice Analyzer tool its cribbing for the AC Tool package and it expects this follow the AEM Cloud package structure guidelines.

Can you please suggest the way forward, so that this package can be deployed that is in compliant with the AEM Cloud guidelines?

Thanks!

**Comment by kwin** [comment]
First of all: The tool runs fine on AEMaaCS.

I ran [Best Practices Analyzer](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/moving/cloud-migration/best-practices-analyzer/using-best-practices-analyzer.html?lang=en#availability) v2.0 on top of a AEM 6.5.5 with ACTool 2.7.1 installed and got the following CSV report row

code | type | subtype | importance | identifier | other | message | moreInfo | context
-- | -- | -- | -- | -- | -- | -- | -- | --
URS | unsupported.repository.structure | package.structure | CRITICAL | Netcentric:accesscontroltool-package:2.7.1 | \N | The Netcentric:accesscontroltool-package:2.7.1 package has both mutable and immutable content. These should be structured into separate packages. | https://www.adobe.com/go/aem_pd_URS | {"data":{"canonicalId":"Netcentric:accesscontroltool-package:2.7.1"},"type":"package.structure"}

This is either due to the fact that the accesscontroltool-package is of type `mixed` while it should be a `container` or the fact that it includes packages in `/etc/packages/` instead of `/apps/...` (to be installed via OSGi installer). Nevertheless I am not aware of any issue with actual deployment to AEM Cloud!

**Comment by kwin** [comment]
We cannot easily switch from subpackages to embeds due to https://github.com/Netcentric/accesscontroltool/issues/451. That would require maintaining separate distributions for AEM Cloud and AEM Classic.

**Comment by kwin** [comment]
With 2.8.0 there is a dedicated `cloud` package which only uses `embeds` instead of `subpackages`.
