### ISSUE TITLE
unmanagedAcePathsRegex feature slows down ACL Tool execution

### ISSUE THREAD

**Issue by insideaem** [Netcentric/accesscontroltool#554]
Hi there,
I am currently working on a project where we use the ACT Tool with lots of yaml files. We've noticed that since the introduction of the unmanagedAcePathsRegex feature, the tool now takes about 5.8h to run instead of about 1h.

Number of YAML files: 1322
Number of Authorizables: 10206
Number of ACEs: 47329
Number of paths: 15001
Runtime: 5.8h

30.10.2020 10:30:46.581 *INFO* biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl *** Starting installation of 10206 authorizables from configuration...
30.10.2020 11:55:40.070 *INFO* biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Finished installation of authorizables without errors in 1.4h
30.10.2020 12:16:42.962 *INFO* biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl *** Starting installation of 47329 ACE configurations for 15001 paths in content nodes using strategy AceBeanInstallerIncremental...
30.10.2020 16:16:33.165 *INFO* biz.netcentric.cq.tools.actool.aceinstaller.BaseAceBeanInstaller ACL Update Statistics: Changed=0 Unchanged=11023 Path not found=3978 (action cache hit/miss=28144/12)
30.10.2020 16:16:33.166 *INFO* biz.netcentric.cq.tools.actool.aceinstaller.BaseAceBeanInstaller *** Finished installation of 15001 ACLs in 4h
30.10.2020 16:16:33.201 *INFO* biz.netcentric.cq.tools.actool.impl.AcInstallationServiceImpl Successfully applied AC Tool configuration in 5.8h
--

We've analyzed it and traced the error back to the call of **getAuthorizableConfigByPrincipalName** in the method **removeUnmanagedPrincipalNamesAtPath**.

Our current solution is to fork the AC Tool and add an OSGI configuration to the AclInstallationServiceImpl to be able to limit the check of the unmanagedAcePathsRegex only to certain authorizable we know we are using the feature in our yaml files.
In our case we only use it for everyone.

I will submit a PR with our changes that you can integrate. Or in case you have a better idea please feel free to implement.

**Comment by ghenzler** [comment]
@insideaem so in general we should avoid a new config property (see https://github.com/Netcentric/accesscontroltool/pull/555/files#r682319005) - if we go down this path it should be somehow "auto-detected" at the very start.

But more generally I'm wondering if it is really  https://github.com/Netcentric/accesscontroltool/blob/2e2727f304256fead1049be72665c0b0287304dd/accesscontroltool-bundle/src/main/java/biz/netcentric/cq/tools/actool/configmodel/AuthorizablesConfig.java#L66 causing this performance degradation, because this is not accessing the repository and purely "in-memory config crunching"... also what version of the AC Tool are you using?

**Comment by ghenzler** [comment]
Looking a bit more into it, it seems it's simply the `O(n2)`  nature of the current implementation - this can be easily improved by using a hashmap lookup by principal id. For the config I tested with execution time went down from 5 to 4 seconds = 20% for ~200 authorizables.

**Comment by ghenzler** [comment]
@insideaem Version `3.0.2` is released and includes the fix  b7cd2811bf7ec3
