### ISSUE TITLE
No JCR trigger for updated ACE configurations

### ISSUE THREAD

**Issue by sbrinkmann** [Netcentric/accesscontroltool#6]
The AEM is designed in a way that OSGi configurations, OSGi Bundles and CRX Packages get installed/applied automatically when they are deployed/updated in the JCR repository. The __Access Control Tool__ requires to execute the tool from the JMX console in order to apply the configuration files. This behavior is against the design of AEM and breaks the functionality to setup a whole AEM instance by just using the package installer. Please align the functionality of the __Access Control Tool__ so that the execute task gets triggered automatically.

**Comment by eliankool** [comment]
In an environment where you install packages in an automated way, I think the JMX version is the preferred one, but I can see that in smaller environments it might make sense to apply these automatically.
Probably adding an option to do so?

**Comment by kwin** [comment]
Currently the ACLTool already comes with an event listener (which would automatically install the YAML files which would be placed there). The path of the event listener is configurable through an OSGi configuration. 
I would like to see an additional automated approach with Install Hooks (http://www.cqblueprints.com/tipsandtricks/packageinstallhook.html). Only that way you can check that the ACLTool was performing correctly (and it is installed at all), because otherwise installation will fail (the process is executed synchronously in contrast to the Event Listener approach). Also there are no timing conflicts with applying the correct OSGi configuration prior to creating the YAML nodes in the repo.

**Comment by sbrinkmann** [comment]
@kwin where can I find this trigger? The current OSGi configuration dialog doesn't show an option for that. How dynamic is the trigger for configurations stored in different places of the JCR?

**Comment by kwin** [comment]
The current mechanism is described at https://github.com/Netcentric/accesscontroltool/blob/master/README.md#uploadlistenerservice.

**Comment by kwin** [comment]
Closed by invalid commit. Not yet fixed.

**Comment by kwin** [comment]
Added a dummy InstallHook in https://github.com/Netcentric/accesscontroltool/commit/7277b9b119c4f47d4ddcf30155198244df4e9910.

**Comment by kwin** [comment]
Also the install hook should be aware of Sling run modes (i.e. install the YAML files only, if the according run mode is set!)

**Comment by kwin** [comment]
The installhook is now documented and can be used from version 1.3 on.
