### ISSUE TITLE
Allow the startup hook to run asynchronously for mutable content

### ISSUE THREAD

**Issue by ghenzler** [Netcentric/accesscontroltool#618]
The AC Tool potentially can run a fairly long time (>1 minute) for mutable content if there is a large magnitude. 

For those cases and when being on AEMaaCS having the AC Tool applied to mutable content via Startup Hook, there should be an option to run the AC Tool asynchronously (to not block startup of pods during AEMaaCS deployment)

To start with this option should not be the default, possibly it makes sense to make it the default later.

**Comment by kwin** [comment]
IMHO we need to distinguish between the two executions of the startup hook
1) During the docker build: It must run synchronously as otherwise the AEM instance may be stopped before the hook finished running
2) During the first real startup we can/should run asynchronously, potentially even with a time delay to make sure that mutable packages are installed first (compare with #545)

**Comment by ghenzler** [comment]
exactly, from description:

> being on AEMaaCS having the AC Tool applied to mutable content via Startup Hook

this is your case 2
