### ISSUE TITLE
Deprecated Service User Mapping Detected 

### ISSUE THREAD

**Issue by gautam-arora** [Netcentric/accesscontroltool#739]
Deprecated Service User Mapping Format Detected

The deprecated format **service:subservice=userId** is still in use and needs to be updated.

Please refactor the mapping to use the supported format **service:subservice=[userId]**.

**NOTE:** The new syntax allows you to use a list with multiple users, enhancing flexibility and security.

For best practices, please visit [Best Practices for Sling Service User Mapping and Service User Definition](https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/best-practices-for-sling-service-user-mapping-and-service-user-definition).

Affected Mapping:

`biz.netcentric.cq.tools.accesscontroltool.bundle=actool-service`
Correct Format:

`biz.netcentric.cq.tools.accesscontroltool.bundle=[actool-service]`
**NOTE:** There might exist other deprecated mappings. Please review all mappings to ensure they are up to date.

**Note from Adobe team -** Please be advised that this deprecated format will be phased out by 31.08.2024. To avoid any disruption, ensure all mappings are updated by this date.

**Comment by kwin** [comment]
According to https://experienceleague.adobe.com/en/docs/experience-manager-cloud-service/content/security/best-practices-for-sling-service-user-mapping-and-service-user-definition also AEM 6.4 supports this format, so this change should be safe.

Note: The principal based mapping is already used since version 2.8.0 for the cloud distribution (https://github.com/Netcentric/accesscontroltool/commit/2309ab95641fdcf46f0402db2b1cc3874ae89c9c)
