### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by gruberroland-netcentric** [Netcentric/accesscontroltool#81]
Restructure readme
* split into multiple files
* add Maven location and installation with precompiled package

**Comment by kwin** [comment]
The information on how run modes are exactly considered is somehow lost. It was there in https://github.com/Netcentric/accesscontroltool/tree/feature/31-or-combination-for-runmodes#installation-hook. Now we only have a short sentence:
> The *.yaml files are installed directly from the package content and respect the runmode semantics. 
(https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#installation-hook)

Since run modes are also considered for JMX now (https://github.com/Netcentric/accesscontroltool/issues/28) and there is also OR semantics supported (https://github.com/Netcentric/accesscontroltool/issues/31) we should add a dedicated section on run modes in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md#installation-hook.

**Comment by gruberroland-netcentric** [comment]
The runmode docs are here: https://github.com/Netcentric/accesscontroltool/blob/develop/docs/Configuration.md

**Comment by kwin** [comment]
very good, didn't see it. Can we have a link towards that section in https://github.com/Netcentric/accesscontroltool/blob/develop/docs/ApplyConfig.md and mention for both JMX and Install Hook that those semantics are considered?
